<?php

return [
    'leagues' => [
        'teams' => 12,
        'meetings' => 2,
    ],
    'cups' => [
        'meetings' => 2,
        'groups' => [
            'meetings' => 2,
        ],
    ],
    'country_code_to_locale' => [
        'SE' => 'sv_SE',
        'US' => 'en_US',
        'GB' => 'en_GB',
        'DE' => 'de_DE',
        'FR' => 'fr_FR',
        'ES' => 'es_ES',
        'IT' => 'it_IT',
        'NL' => 'nl_NL',
        'NO' => 'nb_NO',
        'DK' => 'da_DK',
        'FI' => 'fi_FI',
        'PL' => 'pl_PL',
        'RU' => 'ru_RU',
        'TR' => 'tr_TR',
        'CZ' => 'cs_CZ',
        'HU' => 'hu_HU',
        'PT' => 'pt_PT',
        'RO' => 'ro_RO',
        'SK' => 'sk_SK',
        'BG' => 'bg_BG',
        'EL' => 'el_GR',
        'HR' => 'hr_HR',
        'LT' => 'lt_LT',
        'LV' => 'lv_LV',
        'SR' => 'sr_RS',
        'UK' => 'uk_UA',
        'BE' => 'fr_BE',
        'CA' => 'en_CA',
        'AU' => 'en_AU',
        'NZ' => 'en_NZ',
        'IE' => 'en_IE',
        'ZA' => 'en_ZA',
        'JP' => 'ja_JP',
        'CN' => 'zh_CN',
        'TW' => 'zh_TW',
        'KR' => 'ko_KR',
        'HK' => 'en_HK',
        'SG' => 'en_SG',
        'CR' => 'es_ES',
        'VN' => 'vi_VN',
        'UG' => 'en_UG',
        'KE' => 'en_KE',
        'IN' => 'en_IN',
        'TN' => 'ar_AR',
        'BI' => 'fr_FR',
        'AR' => 'es_ES',
        'BR' => 'pt_BR',
        'IR' => 'fa_IR',
        'SA' => 'ar_SA',
        'BD' => 'bn_BD',
        'AT' => 'de_AT',
        'CH' => 'de_CH',
        'CY' => 'el_CY',
        'GR' => 'el_GR',
        'NG' => 'en_NG',
        'PH' => 'en_PH',
        'PE' => 'es_PE',
        'VE' => 'es_VE',
        'IL' => 'he_IL',
        'ID' => 'id_ID',
        'IS' => 'is_IS',
        'GE' => 'ka_GE',
        'KZ' => 'kk_KZ',
        'ME' => 'me_ME',
        'MY' => 'ms_MY',
        'NP' => 'ne_NP',
        'RS' => 'sr_RS',
        'BF' => 'fr_FR',
    ],
];
